class_name PowerUp
extends Node

enum Type {
	ENERGY_MULTIPLIER,
	ENERGY_FLAT_BONUS,
	ENERGY_HARVEST_SPEED,
	MAX_SHIELD,
	SHIELD_REGENERATION,
	SHIELD_DELAY,
	SHIELD_SPEED,
	PD_SPEED,
	ENERGY_TOTAL_MULTIPLIER_BONUS,
	MAX_SHIPS,
	ORBITAL_PRICE_DECREASE,
	DEFENCE_TURRET_DAMAGE,
	EXPERIENCE_MULTIPLIER,
	LOOT_ENERGY_MULTIPLIER
}